config/routes.rb
MoneyhotelRails::Application.routes.draw do
  resources :news

  resources :posts

  resources :entries

  resources :ids

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/models/id.rb
class Id < ActiveRecord::Base
end

app/models/new.rb
class New < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, :notice => 'Entry was successfully created.' }
        format.json { render :json => @entry, :status => :created, :location => @entry }
      else
        format.html { render :action => "new" }
        format.json { render :json => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, :notice => 'Entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :ok }
    end
  end
end

app/controllers/ids_controller.rb
class IdsController < ApplicationController
  # GET /ids
  # GET /ids.json
  def index
    @ids = Id.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ids }
    end
  end

  # GET /ids/1
  # GET /ids/1.json
  def show
    @id = Id.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @id }
    end
  end

  # GET /ids/new
  # GET /ids/new.json
  def new
    @id = Id.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @id }
    end
  end

  # GET /ids/1/edit
  def edit
    @id = Id.find(params[:id])
  end

  # POST /ids
  # POST /ids.json
  def create
    @id = Id.new(params[:id])

    respond_to do |format|
      if @id.save
        format.html { redirect_to @id, :notice => 'Id was successfully created.' }
        format.json { render :json => @id, :status => :created, :location => @id }
      else
        format.html { render :action => "new" }
        format.json { render :json => @id.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ids/1
  # PUT /ids/1.json
  def update
    @id = Id.find(params[:id])

    respond_to do |format|
      if @id.update_attributes(params[:id])
        format.html { redirect_to @id, :notice => 'Id was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @id.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ids/1
  # DELETE /ids/1.json
  def destroy
    @id = Id.find(params[:id])
    @id.destroy

    respond_to do |format|
      format.html { redirect_to ids_url }
      format.json { head :ok }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = New.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = New.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = New.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = New.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = New.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, :notice => 'New was successfully created.' }
        format.json { render :json => @news, :status => :created, :location => @news }
      else
        format.html { render :action => "new" }
        format.json { render :json => @news.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = New.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, :notice => 'New was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @news.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = New.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_url }
      format.json { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/ids_helper.rb
module IdsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.title %></td>
    <td><%= entry.text %></td>
    <td><%= link_to 'Show', entry %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>

<p>
  <b>Text:</b>
  <%= @entry.text %>
</p>


<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/ids/_form.html.erb
<%= form_for(@id) do |f| %>
  <% if @id.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@id.errors.count, "error") %> prohibited this id from being saved:</h2>

      <ul>
      <% @id.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ids/edit.html.erb
<h1>Editing id</h1>

<%= render 'form' %>

<%= link_to 'Show', @id %> |
<%= link_to 'Back', ids_path %>

app/views/ids/index.html.erb
<h1>Listing ids</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ids.each do |id| %>
  <tr>
    <td><%= link_to 'Show', id %></td>
    <td><%= link_to 'Edit', edit_id_path(id) %></td>
    <td><%= link_to 'Destroy', id, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Id', new_id_path %>

app/views/ids/new.html.erb
<h1>New id</h1>

<%= render 'form' %>

<%= link_to 'Back', ids_path %>

app/views/ids/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_id_path(@id) %> |
<%= link_to 'Back', ids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoneyhotelRails</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= link_to 'Show', news %></td>
    <td><%= link_to 'Edit', edit_news_path(news) %></td>
    <td><%= link_to 'Destroy', news, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New New', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>